name: Run tests

on:
  push:
    branches:
      - main
      - develop
      - '**-develop'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7.11, 3.8.15, 3.9.16,3.10.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r src/subtitle_utils/requirements.txt
          python -m pip install pytest

      - name: Run tests
        run: |
          python test/test_method.py